# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField(verbose_name='description')),
                ('link', models.URLField()),
                ('code', models.CharField(blank=True, max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('ishot', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='date modification')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('desc', models.TextField(verbose_name='description')),
                ('link', models.URLField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('ishot', models.BooleanField(default=False)),
                ('logo', models.ImageField(upload_to='logos')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='date modification')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='br_colpon.Store'),
        ),
    ]
